### ISSUE TITLE
Question: how to work in dev with src dir and in prod with dist dir?

### ISSUE THREAD

**Issue by lucasmogari** [patrick-steele-idem/require-self-ref#2]
Is there a way to replace the base dir for different environment or what would be a better solution for different dirs (src/dist/build)?

**Comment by patrick-steele-idem** [comment]
Hey @lucasmogari, `require-self-ref` works by walking up the directory tree to find a `package.json` field with a non-empty `name` field to determine what is the "root directory" of the package. Therefore, you could create separate root directories by putting a `package.json` in your `src/` directory and a `package.json` in your `dist` directory. The `package.json` files just need to have a non-empty `name` field such as the following:

``` json
{
  "name": "my-app/src"
}
```

Does that work for you? We should probably better document this if so.

**Comment by lucasmogari** [comment]
Yes, it works! Thank you and I'm sorry for taking so long to answer.
