### ISSUE TITLE
Add an option to change lookup folder inside project's root

### ISSUE THREAD

**Issue by dackmin** [patrick-steele-idem/require-self-ref#3]
Even knowing the reason behind the need of project's `name` property in `package.json` file, I was thinking about adding the ability to specify (either as a `package.json` property or a `self-ref.json` config file, maybe) a sub directory inside project's root.

As a long-time user of CoffeeScript, I always build every cs file into a `build/` folder inside project's root, which breaks the current behavior of `require-self-ref`.
Obviously, editing every `require "~/...` into `require "~/build/...` would be an option, but when you have a shit-load of files, you don't really want to do that... 😄 

I would really enjoy making a pull request and suggest some edits, but I'm not sure about what is the best way to provide this option.

Any thoughts ?

Edit 1 : After carefully reading the previous issue, I will add "without changing my app name inside `package.json` file"

**Comment by patrick-steele-idem** [comment]
Couldn't you create an additional `build/package.json` file with a `name` property?

**Comment by dackmin** [comment]
yep that's what I ended up doing, using a `grunt-copy` task, but I primarily wanted to avoid that as much as possible.
